server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/svmsharma20/RentMyCarApp
          search-paths:
           - '/config-store'
           - '/config-store/*service'
